### ISSUE TITLE
npm run clean not working in windows

### ISSUE THREAD

**Issue by MelissaMMDP** [damonbauer/npm-build-boilerplate#6]
When I enter npm run clean I receive the error:

`
'rm' is not recognized as an internal or external command, operable program or batch file.
`

When I change rm to del I then receive this error:

`
Invalid switch - "{css".
`

Can anyone tell me how I need to rewrite the npm scripts file paths so that windows will not throw an error?

**Comment by damonbauer** [comment]
hey @MAustinMMDP, try installing `rimraf` (https://www.npmjs.com/package/rimraf). Windows doesn't have `rm`, so this package aims to replicate it.

Instead of `rm -f dist/{css/*,js/*,images/*}`, it'd be something like: `rimraf dist/{css/*,js/*,images/*}`.

You'll also run into `mkdir -p` issues, if you try to use that (used in the `uglify` task). For that, I'd recommend installing the `mkdirp` module: https://github.com/substack/node-mkdirp.
